[raku]
format = "via [$symbol]($style)"

[erlang]
format = "via [$symbol]($style)"

[docker_context]
symbol = "ïŒˆ "

[pulumi]
format = "via [$symbol$stack]($style)"

[golang]
symbol = "î˜§ "

[haxe]
symbol = "î™¦ "

[typst]
format = "via [$symbol]($style)"

[rust]
symbol = "ó±˜— "

[guix_shell]
symbol = "ïŒ¥ "

[crystal]
symbol = "î˜¯ "

[fossil_branch]
symbol = "ï˜ "

[swift]
symbol = "î• "

[helm]
format = "via [$symbol]($style)"

[git_commit]
tag_symbol = " ï’ "

[julia]
symbol = "î˜¤ "

[ruby]
symbol = "î‘ "

[zig]
symbol = "îš© "

[purescript]
format = "via [$symbol]($style)"

[os.symbols]
Solus = "ó° ³ "
Macos = "ïŒ‚ "
Unknown = "ïˆ­ "
Pop = "ïŒª "
Fedora = "ïŒŠ "
OpenBSD = "ó°ˆº "
Linux = "ïŒš "
openSUSE = "ïŒ” "
Mint = "ïŒ "
Arch = "ïŒƒ "
DragonFly = "îŠ "
Windows = "ó°² "
Illumos = "ó°ˆ¸ "
FreeBSD = "ïŒŒ "
CentOS = "ïŒ„ "
Emscripten = "ïˆ… "
Debian = "ïŒ† "
Mariner = "ï‡ "
EndeavourOS = "ï†— "
Artix = "ïŒŸ "
Ubuntu = "ïŒ› "
Manjaro = "ïŒ’ "
Alpaquita = "îª¢ "
Void = "ïŒ® "
MidnightBSD = "ï†† "
OracleLinux = "ó°Œ· "
RockyLinux = "ïŒ« "
Android = "ï…» "
RedHatEnterprise = "ïŒ– "
Garuda = "ó°›“ "
Redox = "ó°€˜ "
NixOS = "ïŒ“ "
Alpine = "ïŒ€ "
CachyOS = "ïŒƒ "
Redhat = "ïŒ– "
Mabox = "î¬© "
Amazon = "ï‰° "
Gentoo = "ïŒ "
AlmaLinux = "ïŒ "
NetBSD = "ï€¤ "
Kali = "ïŒ§ "
Raspbian = "ïŒ• "
SUSE = "ïŒ” "
Nobara = "ï€ "
HardenedBSD = "ó°Œ "

[meson]
symbol = "ó°”· "

[gradle]
symbol = "î™  "

[opa]
format = "via [$symbol]($style)"

[pijul_channel]
symbol = "ï˜ "

[aws]
symbol = "îŒ½  "

[hg_branch]
symbol = "ï˜ "

[bun]
symbol = "î¯ "

[cpp]
symbol = "î˜ "

[dotnet]
format = "[$symbol(ğŸ¯ $tfm )]($style)"

[python]
symbol = "îˆµ "

[red]
format = "via [$symbol]($style)"

[fennel]
symbol = "îš¯ "

[c]
symbol = "î˜ "

[git_branch]
symbol = "ï˜ "

[package]
symbol = "ó°— "

[rlang]
symbol = "ó°Ÿ” "

[gcloud]
symbol = "îŒ½  "

[lua]
symbol = "î˜  "

[vlang]
format = "via [$symbol]($style)"

[cmake]
symbol = "î” "

[memory_usage]
symbol = "ó°› "

[scala]
symbol = "îœ· "

[perl]
symbol = "î™¾ "

[cobol]
format = "via [$symbol]($style)"

[directory]
read_only = " ó°Œ¾"

[pixi]
symbol = "ó°— "

[deno]
symbol = "îŸ€ "

[vagrant]
format = "via [$symbol]($style)"

[dart]
symbol = "î˜ "

[ocaml]
symbol = "î™º "

[quarto]
format = "via [$symbol]($style)"

[php]
symbol = "î˜ˆ "

[java]
symbol = "î‰– "

[elixir]
symbol = "î˜­ "

[kotlin]
symbol = "î˜´ "

[haskell]
symbol = "î· "

[buf]
symbol = "ï’ "

[nim]
symbol = "ó°†¥ "

[hostname]
ssh_symbol = "î¬ "

[daml]
format = "via [$symbol]($style)"

[gleam]
format = "via [$symbol]($style)"

[conda]
symbol = "ï„Œ "

[solidity]
format = "via [$symbol]($style)"

[elm]
symbol = "î˜¬ "

[nix_shell]
symbol = "ïŒ“ "

[nodejs]
symbol = "îœ˜ "
